on: [push]

name: CI

jobs:
  build_and_test:
    name: Test Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache target
        uses: actions/cache@v2
        env:
          cache-name: cache-default-target-and-lockfile
        with:
          path: |
            target
            Cargo.lock
            ~/.rustup
          key: ${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo build --all-features
      - run: cargo test --all-features -- --skip session --skip quit_and_rejoin_session
      - run: cargo clippy -- -Dwarnings
